// Generated by CoffeeScript 1.9.1
(function() {
  "use strict";
  var swapReverse;

  swapReverse = function(array) {
    var head, isString, stop, tail, temp;
    if (array == null) {
      array = [];
    }
    isString = typeof array === 'string';
    if (isString) {
      array = array.split('');
    }
    head = 0;
    tail = array.length - 1;
    stop = tail / 2;
    while (head < stop) {
      temp = array[head];
      array[head] = array[tail];
      array[tail] = temp;
      head++;
      tail--;
    }
    if (isString) {
      array = array.join('');
    }
    return array;
  };

  if ((typeof define !== "undefined" && define !== null) && ('function' === typeof define) && define.amd) {
    define('swapReverse', [], function() {
      return swapReverse;
    });
  } else if (typeof module !== 'undefined') {
    module.exports = swapReverse;
  }

}).call(this);
